#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff
#

# global settings
yabai -m config                                 \
    external_bar                 all:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.9            \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    window_insertion_point       last          \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   08             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap


yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^CleanShot X$" manage=off


echo "yabai configuration loaded.."

# SketchyBar integration - send space change signals
yabai -m signal --add event=space_changed action="sketchybar --trigger space_change"
yabai -m signal --add event=display_changed action="sketchybar --trigger space_change"

# Window and app tracking signals
yabai -m signal --add event=window_focused action="sketchybar --trigger front_app_switched"
yabai -m signal --add event=window_created action="sketchybar --trigger space_windows_change"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger space_windows_change"
